# Generated by Django 5.0.6 on 2024-06-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_fecha_nacimiento_cliente_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_nacimiento',
        ),
    ]
