# Generated by Django 5.0.6 on 2024-06-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_bicicleta_alter_cliente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bicicletas/'),
        ),
    ]
