# Generated by Django 5.0.6 on 2024-06-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_bicicleta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='forma_pago',
            field=models.CharField(choices=[('Debito', 'Débito'), ('Credito', 'Crédito'), ('Transferencia', 'Transferencia Bancaria')], max_length=20),
        ),
    ]
