# Generated by Django 5.0.6 on 2024-06-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_bicicleta_precio_por_dia_alter_arriendo_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio_por_dia',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
