# Generated by Django 5.0.6 on 2024-06-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_bicicleta_precio_por_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='costo_arriendo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='deposito_garantia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
