# Generated by Django 5.0.6 on 2024-06-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_arriendo_costo_arriendo_arriendo_costo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='precio_por_dia',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
    ]
