# Generated by Django 5.0.6 on 2024-06-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_bicicleta_precio_por_dia_delete_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='tipo',
            field=models.CharField(choices=[('MTB', 'Montaña'), ('RDB', 'Ruta'), ('CTY', 'Ciudad'), ('BMX', 'BMX')], max_length=3),
        ),
    ]
