# Generated by Django 5.0.6 on 2024-06-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_bicicleta_stock_alter_bicicleta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='disponible_para_arriendo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='disponible_para_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio_por_dia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
