# Generated by Django 5.0.6 on 2024-06-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_bicicleta_disponible_para_arriendo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
