# Generated by Django 5.0.6 on 2024-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_arriendo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
