# Generated by Django 5.0.6 on 2024-06-26 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_arriendo_id'),
        ('tecnicos_vendedores', '0002_reservatecnico_esta_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_bicicleta', models.CharField(max_length=100)),
                ('tipo_bicicleta', models.CharField(choices=[('MTB', 'Montaña'), ('RDB', 'Ruta'), ('CTY', 'Ciudad'), ('BMX', 'BMX')], max_length=3)),
                ('descripcion_problema', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparaciones', to=settings.AUTH_USER_MODEL)),
                ('reserva_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos_vendedores.reservatecnico')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialMantencion',
        ),
    ]
