# Generated by Django 5.0.6 on 2024-06-26 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_reparacion_delete_historialmantencion'),
        ('tecnicos_vendedores', '0002_reservatecnico_esta_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='reserva_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnicos_vendedores.reservatecnico'),
        ),
    ]
