# Generated by Django 5.0.6 on 2024-06-26 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_reparacion_reserva_tecnico'),
        ('tecnicos_vendedores', '0002_reservatecnico_esta_disponible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reparación', 'verbose_name_plural': 'Reparaciones'},
        ),
        migrations.AddField(
            model_name='reparacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='reserva_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones', to='tecnicos_vendedores.reservatecnico'),
        ),
    ]
