# Generated by Django 5.0.6 on 2024-06-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_alter_bicicleta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='estado_reparacion',
            field=models.CharField(choices=[('EP', 'Esperando Producto'), ('ER', 'En Reparacion'), ('LR', 'Listo para el Retiro')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
