# Generated by Django 5.0.6 on 2024-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_reparacion_estado_reparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='estado_reparacion',
            field=models.CharField(choices=[('Esperando producto.', 'Esperando Producto'), ('En reparacion', 'En Reparacion'), ('Listo para retirar', 'Listo para el Retiro')], max_length=25),
        ),
    ]
