# Generated by Django 5.0.6 on 2024-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('Procesando Pedido', 'Procesando'), ('Pedido Confirmado', 'Confirmado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='Procesando Pedido', max_length=20),
        ),
    ]
