# Generated by Django 5.0.6 on 2024-07-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carro', '0003_codigodescuento_orden_codigo_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='codigo_descuento',
        ),
        migrations.DeleteModel(
            name='CodigoDescuento',
        ),
    ]
