# Generated by Django 5.0.6 on 2024-06-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos_vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservatecnico',
            name='esta_disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservatecnico',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tecnicos_vendedores.tecnico'),
        ),
        migrations.DeleteModel(
            name='Reparacion',
        ),
    ]
