# Generated by Django 5.0.6 on 2024-06-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos_vendedores', '0004_alter_venta_vendedor_alter_ventadetalle_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
    ]
