# Generated by Django 5.0.6 on 2024-07-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnicos_vendedores', '0007_alter_tecnico_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='especialidad',
            field=models.CharField(choices=[('Montaña', 'Montaña'), ('Ruta', 'Ruta'), ('Ciudad', 'Ciudad'), ('BMX', 'BMX')], max_length=10),
        ),
    ]
